import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,createState,TIERS,DEPTS,done,agentTarget,activeRules} from '../engine.js';
const item=(overrides={})=>({id:'test',name:'Test work',lane:'primary',dept:'Cabins',status:2,points:20,tag:'Normal',stuck:false,stuckRisk:0,...overrides});
function fixture(ids=[],items=[item()]){const s=createState(42);Object.assign(s,{phase:'playing',day:1,actions:6,tier:'enterprise',items,automations:ids.map(id=>({id,enabled:true}))});return new Game(s);}

test('same seed and decisions reproduce days, shop and scores',async()=>{
  const a=new Game(createState(73)),b=new Game(createState(73));
  for(const g of [a,b]){await g.startDay();while(g.s.phase==='playing'){if(g.s.pendingStuck){await g.resolveStuck(g.s.coins>=3?'coins':'actions');continue;}const t=g.s.items.find(i=>i.lane==='primary'&&!done(i))||g.s.items.find(i=>!done(i));if(t)await g.act(t.id);else await g.endDay();}}
  assert.deepEqual(a.s,b.s);assert.equal(a.s.phase,'shop');
});
test('failure is mandatory completion, never score',async()=>{const g=fixture();g.s.dayScore=10000;await g.endDay();assert.equal(g.s.phase,'lost');const h=fixture([], [item({status:3})]);await h.endDay();assert.equal(h.s.phase,'shop');assert.equal(h.s.coins,4);});
test('preparation follows the shared status track and carries its exact saved status',async()=>{const g=fixture([], [item({id:'prep',lane:'secondary',targetId:'tomorrow',status:0,points:5})]);g.s.tomorrow=[item({id:'tomorrow',status:0,prepared:0}),item({id:'other',status:0,prepared:0})];await g.act('prep');assert.equal(g.s.items[0].status,1);assert.equal(g.s.tomorrow[0].prepared,0);await g.act('prep');assert.equal(g.s.items[0].status,2);await g.act('prep');assert.equal(g.s.tomorrow[0].prepared,1);assert.equal(g.s.tomorrow[0].preparedStatus,1);assert.equal(g.s.tomorrow[1].prepared,0);await g.endDay();await g.startDay();const tomorrow=g.s.items.find(i=>i.id==='tomorrow');assert.equal(tomorrow.status,1);await g.act('tomorrow');assert.equal(tomorrow.status,2);assert.equal(g.s.items.find(i=>i.id==='other').status,0);});
test('prepared bosses still start Pending and save their first status step',async()=>{const g=fixture([]);g.s.phase='shop';g.s.day=2;g.s.tomorrow=[item({id:'prepared-boss',status:0,prepared:1,boss:true}),item({id:'unprepared-boss',status:0,prepared:0,boss:true})];await g.startDay();assert.equal(g.s.items[0].status,0);assert.equal(g.s.items[1].status,0);await g.act('prepared-boss');assert.equal(g.s.items[0].status,2);});
test('a review can become Stuck and the player chooses coins or actions to finish it',async()=>{const coins=fixture([], [item({id:'coin-route',stuckRisk:1})]);coins.s.coins=3;await coins.act('coin-route');assert.equal(coins.s.items[0].stuck,true);assert.equal(coins.s.pendingStuck,'coin-route');assert.equal(await coins.endDay(),false);await coins.resolveStuck('coins');assert.equal(coins.s.items[0].status,3);assert.equal(coins.s.coins,0);assert.equal(coins.s.pendingStuck,null);const actions=fixture([], [item({id:'action-route',stuckRisk:1})]);await actions.act('action-route');assert.equal(actions.s.actions,5);await actions.resolveStuck('actions');assert.equal(actions.s.items[0].status,3);assert.equal(actions.s.actions,3);});
test('tier upgrades are sequential, affordable and capacity-derived',()=>{const g=fixture();Object.assign(g.s,{phase:'shop',tier:'basic',coins:7,automations:[]});assert.equal(g.upgrade(),false);g.s.coins=24;assert.equal(g.hire('coordinator'),false);assert.equal(g.upgrade(),true);assert.equal(g.s.tier,'pro');assert.equal(g.s.coins,16);assert.equal(g.upgrade(),true);assert.equal(g.s.tier,'enterprise');assert.equal(g.s.coins,0);assert.equal(g.upgrade(),false);assert.deepEqual(Object.values(TIERS).map(t=>[t.automations,t.agents]),[[2,0],[5,2],[8,4]]);});
test('buying at capacity puts automation in reserve and blocks excess activation',()=>{const g=fixture(['assign','bonus']);Object.assign(g.s,{phase:'shop',tier:'basic',coins:20,offers:['galley']});assert.equal(g.buy('galley'),true);assert.equal(g.toggle('galley'),false);assert.equal(g.toggle('bonus'),true);assert.equal(g.toggle('galley'),true);assert.deepEqual(activeRules(g.s),['assign','galley']);g.s.phase='playing';assert.equal(g.toggle('assign'),false);assert.equal(g.sell('assign'),false);assert.equal(g.reorder('assign',1),false);});
test('agent selection prioritizes lane, proximity to Done, then board order',()=>{const g=fixture([], [item({id:'r',lane:'recurring'}),item({id:'s',lane:'secondary',status:0}),item({id:'p1',status:0}),item({id:'p2',status:2}),item({id:'p3',status:2}),item({id:'wrong',dept:'Deck'})]);const a={dept:'Cabins'};assert.equal(agentTarget(g.s,a).id,'p2');g.s.items.filter(i=>i.lane==='primary'&&i.dept==='Cabins').forEach(i=>i.status=3);assert.equal(agentTarget(g.s,a).id,'s');g.s.items[1].status=3;assert.equal(agentTarget(g.s,a).id,'r');});
test('agents act once per player action, never once per triggered effect',async()=>{const g=fixture(['bonus','galley'],[item({id:'player',dept:'Deck'}),item({id:'agent',dept:'Galley',status:0})]);g.s.agents=[{id:'coordinator',dept:'Galley'}];await g.act('player');assert.equal(g.s.items[1].status,1);assert.equal(g.s.actions,5);});
test('completion bonuses and VIP agent bonus receive Cabin and VIP multipliers',async()=>{const g=fixture(['bonus','room','vip'],[item({id:'click',dept:'Deck',status:0}),item({id:'vip',tag:'VIP'})]);g.s.agents=[{id:'liaison',dept:'Cabins'}];await g.act('click');assert.equal(g.s.dayScore,(20+5+10)*1.5*2);});
test('Chain Reaction retroactively doubles the entire action score once',async()=>{const g=fixture(['bonus','room','vip','chain'],[item({tag:'VIP'})]);await g.act('test');assert.equal(g.s.dayScore,(20+5)*1.5*2*2);assert.equal(g.s.log.filter(e=>e.kind==='multiplier').length,1);});
test('Touch Base sends Review back once per task each day, then lets it complete',async()=>{const g=fixture(['touch'],[item({status:1})]);await g.act('test');assert.equal(g.s.items[0].status,1);assert.equal(g.s.dayScore,10);const c=g.context();for(let n=0;n<5;n++){await g.advance(c,g.s.items[0]);await g.drain(c);}assert.equal(g.s.daily['touch-test'],true);assert.equal(g.s.items[0].status,3);});
test('Crossover asks for a target and resolves its effects before next agent',async()=>{const g=fixture(['cross','galley'],[item({id:'deck',dept:'Deck'}),item({id:'galley1',dept:'Galley',status:0}),item({id:'galley2',dept:'Galley',status:0})]);g.choose=async()=> 'galley2';await g.act('deck');assert.equal(g.s.items[1].status,0);assert.equal(g.s.items[2].status,1);assert.equal(g.s.dayScore,23);});
test('Stuck alert is capped twice daily and Escalation Manager once daily',async()=>{const g=fixture(['alert']);g.s.agents=[{id:'escalation',dept:'Cabins'}];for(let n=0;n<4;n++){const c=g.context();c.queue.push({type:'stuck',item:g.s.items[0]});await g.drain(c);}assert.equal(g.s.actions,9);});
test('Sign-off Specialist approves once daily, with normal completion payouts',async()=>{const g=fixture(['bonus'],[item({id:'click',dept:'Deck',status:0}),item({id:'sign',status:1})]);g.s.agents=[{id:'signoff',dept:'Cabins'}];await g.act('click');assert.equal(g.s.items[1].status,3);assert.equal(g.s.dayScore,25);assert.equal(g.s.daily['perk-signoff'],true);});
test('Coordinator and Quartermaster perks stay attributed to their own completions',async()=>{const g=fixture([],[item({id:'click',dept:'Deck',status:0}),item({id:'prep',lane:'secondary',points:5,status:2}),item({id:'recurring',dept:'Galley',lane:'recurring',points:15})]);g.s.agents=[{id:'coordinator',dept:'Cabins'},{id:'quartermaster',dept:'Galley'}];await g.act('click');assert.equal(g.s.dayScore,23);assert.equal(g.s.coins,1);});
test('successful-day rewards fund upkeep before Overtime; final day does not buy overtime',async()=>{const g=fixture(['overtime'],[item({status:3})]);g.s.dayScore=80;g.s.agents=[{id:'coordinator',dept:'Cabins'}];await g.endDay();assert.equal(g.s.coins,3);assert.equal(g.s.nextActions,2);await g.startDay();assert.equal(g.s.actions,8);const h=fixture(['overtime'],[item({status:3})]);h.s.day=10;await h.endDay();assert.equal(h.s.phase,'won');assert.equal(h.s.coins,4);assert.equal(h.s.nextActions,0);});
test('unpaid agents leave in slot order',async()=>{const g=fixture([],[item({status:3})]);g.s.coins=-3;g.s.agents=[{id:'coordinator',dept:'Cabins'},{id:'liaison',dept:'Deck'}];await g.endDay();assert.deepEqual(g.s.agents,[{id:'coordinator',dept:'Cabins'}]);});
test('global guard stops at 50 effects and per-rule guard stops at 5',async()=>{const g=fixture();const c=g.context();for(let n=0;n<8;n++)await g.fire(c,'bonus');assert.equal(c.fires.bonus,5);for(let n=0;n<50;n++)await g.fire(c,`effect-${n}`);assert.equal(c.effects,50);assert.equal(c.halted,true);});
test('hire and assignment enforce phase, capacity and valid department',()=>{const g=fixture();Object.assign(g.s,{phase:'shop',tier:'pro',coins:30});assert.equal(g.hire('coordinator','Galley'),true);assert.equal(g.hire('coordinator','Cabins'),false);assert.equal(g.hire('liaison','Deck'),true);assert.equal(g.hire('quartermaster','Cabins'),false);assert.equal(g.assign('coordinator','Nowhere'),false);g.s.phase='playing';assert.equal(g.assign('coordinator','Cabins'),false);});
test('Daily Standup advances distinct eligible orders, leaving preparations untouched',async()=>{const g=fixture(['standup']);g.s.phase='shop';g.s.tomorrow=[item({id:'one',status:0,prepared:0}),item({id:'two',status:0,prepared:0})];await g.startDay();assert.equal(g.s.items.filter(i=>i.lane!=='secondary').reduce((sum,i)=>sum+i.status,0),2);assert.ok(g.s.items.filter(i=>i.lane==='secondary').every(i=>i.status===0));assert.equal(g.s.log.filter(e=>e.source==='standup'&&e.kind==='advance').length,2);});
test('Clear Blockers can clear a selected active blocker back to Working',async()=>{const g=fixture(['clear'],[item({id:'one',stuck:true}),item({id:'two',stuck:true})]);const c=g.context();await g.advance(c,g.s.items[1],'clear',true);await g.drain(c);assert.equal(g.s.items[0].stuck,true);assert.equal(g.s.items[1].stuck,false);assert.equal(g.s.items[1].status,1);});
test('Fast Track can refund the final player action and Momentum counts agent advances',async()=>{const g=fixture(['fast','momentum'],[item({id:'urgent',tag:'Urgent'}),item({id:'agent',dept:'Galley',status:0})]);g.s.agents=[{id:'coordinator',dept:'Galley'}];g.s.actions=1;await g.act('urgent');assert.equal(g.s.actions,1);assert.equal(g.s.phase,'playing');assert.equal(g.s.dayScore,23);});
test('legacy cruises retain their original conservative balance',async()=>{
  let wins=0,enterprise=0;
  for(let seed=1;seed<=100;seed++){const legacy=createState(seed);delete legacy.balanceVersion;const g=new Game(legacy);await g.startDay();while(g.s.phase!=='lost'&&g.s.phase!=='won'){
    if(g.s.phase==='shop'){if(g.s.tier==='basic'&&g.s.coins>=12)g.upgrade();if(g.s.tier==='pro'&&g.s.agents.length===0&&g.s.coins>=5)g.hire('coordinator',DEPTS[(g.s.day)%4]);if(g.s.tier==='pro'&&g.s.coins>=24)g.upgrade();if(g.s.agents.length)g.assign('coordinator',DEPTS[g.s.day%4]);await g.startDay();continue;}
    if(g.s.pendingStuck){await g.resolveStuck(g.s.coins>=3?'coins':'actions');continue;}const target=g.s.items.find(i=>i.lane==='primary'&&!done(i))||g.s.items.find(i=>i.lane==='secondary'&&!done(i))||g.s.items.find(i=>!done(i));if(target)await g.act(target.id);else await g.endDay();
  }if(g.s.phase==='won')wins++;if(g.s.tier==='enterprise')enterprise++;}
  assert.ok(wins>=70,`Only ${wins}/100 wins for conservative policy`);assert.ok(enterprise>=50,`Only ${enterprise}/100 reached Enterprise`);
});
