import {Game,createState,DEPTS,TIERS,RULES,AGENTS,BOSSES,DISRUPTIONS,status,done,activeRules} from './engine.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey='all-a-board-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(storageKey));}catch{}
let state=saved?.version===2&&Array.isArray(saved.items)&&TIERS[saved.tier]?saved:createState();
let view='board',search='',ruleSearch='',ruleRarity='All rarities',groupBy='eta',busy=false,highlight=null,agentAction=null,selectedAgent='coordinator',speed=1,collapsed=new Set();
try{speed=Number(localStorage.getItem('aab-speed')??1);}catch{}
let game;
const icons={board:'▦',automations:'⚡',agents:'♧',shop:'＋'};
const laneInfo={primary:{name:'Primary goals',color:'#008b62',label:'Due today · required to stay aboard'},secondary:{name:'Prepare for tomorrow',color:'#0089c9',label:'Optional · one less step tomorrow'},recurring:{name:'Recurring tasks',color:'#e43891',label:'Optional · a little extra credit'}};
const rules=()=>activeRules(state);
const portrait=(a,extra='')=>`<span class="portrait p${a.portrait} ${extra}" role="img" aria-label="${esc(a.name)} portrait"></span>`;
const canManage=()=>state.phase==='shop'&&!busy;
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}}
function buildGame(){game=new Game(state,{choose:chooseTarget,onEvent:async e=>{
  const isAgentTurn=e.kind==='trigger'&&AGENTS.some(a=>a.id===e.source);
  agentAction=isAgentTurn?{id:e.source,target:e.target}:null;highlight=e;render();$('#announcer').textContent=isAgentTurn?`${AGENTS.find(a=>a.id===e.source).name} is taking an action on ${state.items.find(i=>i.id===e.target)?.name||'work'}.`:e.message;
  const source=document.querySelector(`[data-source="${e.source}"]`),target=document.getElementById(e.target);
  if(e.kind==='stuck'){
    target?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});
    const warning=document.createElement('div');warning.className='stuck-warning';warning.setAttribute('role','alert');warning.innerHTML=`<strong>WORK STOPPED</strong><span>${esc(state.items.find(i=>i.id===e.target)?.name||'Task')} is Stuck</span>`;
    document.body.append(warning);document.body.classList.add('incident-active');target?.classList.add('stuck-impact');
    try{await new Promise(resolve=>setTimeout(resolve,2000));}finally{warning.remove();document.body.classList.remove('incident-active');target?.classList.remove('stuck-impact');}
  }
  if(source&&target&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),duration=isAgentTurn?1150:600;const line=document.createElement('div');line.className=`cascade-line ${isAgentTurn?'agent-cascade-line':''}`;const x=a.left+a.width/2,y=a.top+a.height/2,dx=b.left+30-x,dy=b.top+b.height/2-y;Object.assign(line.style,{left:`${x}px`,top:`${y}px`,width:`${Math.hypot(dx,dy)}px`,transform:`rotate(${Math.atan2(dy,dx)}rad)`,animationDuration:`${duration}ms`});document.body.append(line);setTimeout(()=>line.remove(),duration);}
  if(e.kind==='reset')target?.classList.add('inspection-reset');
  if(speed&& !matchMedia('(prefers-reduced-motion: reduce)').matches)await new Promise(r=>setTimeout(r,(isAgentTurn?1150:['disruption','reset','agent-skip'].includes(e.kind)?1000:e.kind==='trigger'?280:160)/speed));
  if(isAgentTurn){agentAction=null;render();}
}});}
function button(text,action,attrs='',cls=''){return `<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;}
function disabled(condition){return condition?'disabled':'';}
function render(){
  const focused=document.activeElement?.dataset;const focusAction=focused?.action,focusId=focused?.id;
  const cap=TIERS[state.tier],primary=state.items.filter(i=>i.lane==='primary'),complete=primary.filter(done).length;
  $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#" aria-label="All A Board home"><span class="brand-mark"><i></i><i></i><i></i></span><strong>all a board<span>cruise operations</span></strong></a><div class="workspace-label">WORKSPACE <span>⌄</span></div><div class="workspace"><span class="workspace-icon">A</span> All A Board! <span>⌄</span></div><nav>${Object.keys(icons).map(v=>button(`<span>${icons[v]}</span>${{board:'Work board',automations:'Automations',agents:'Agents',shop:'Port of call'}[v]}${v==='shop'&&state.phase==='shop'?'<i class="dot"></i>':''}`,'view',`data-view="${v}" aria-current="${view===v?'page':'false'}"`,view===v?'nav-active':'')).join('')}</nav><div class="sidebar-note"><span>☀</span><strong>A very normal cruise.</strong><p>Exceptional service.<br/>Occasional supernatural incident.</p></div><div class="plan-chip"><span class="tier-icon">✦</span><div><strong>${state.tier.toUpperCase()}</strong><small>${cap.automations} automations · ${cap.agents} agents</small></div></div></aside>
  <main><header class="topbar"><div class="breadcrumb">Workspace <span>/</span> Cruise operations</div><div class="top-actions"><span class="seed">Seed ${state.seed}</span>${button('↻ New cruise','restart','','quiet')}${button('?', 'help','aria-label="How to play"','help-button')}</div></header>
  <section class="page-heading"><div><div class="eyebrow">ALL A BOARD! <span class="mini-wave">≈</span> OPERATIONS AT SEA</div><h1>${{board:'Cruise operations',automations:'Manage your board automations',agents:'Meet your crew',shop:'Your next unfair advantage'}[view]} ${view==='board'?'<span class="title-chevron">⌄</span>':''}</h1><p>${{board:'Keep the ship running. Prepare for tomorrow. Try not to get fired.',automations:'A little less manual work. A lot more “that was supposed to happen.”',agents:'Subject-matter experts. Questionable sea legs.',shop:'The day is done. Put your hard-earned coins to work.'}[view]}</p></div><div class="heading-action">${view==='board'?button('⚡ Automate','view','data-view="automations"','quiet')+button(`♧ Agents / ${state.agents.length}`,'view','data-view="agents"','quiet'):button('← Back to board','view','data-view="board"','quiet')}</div></section>
  <div class="tabbar">${button(view==='board'?'Main table':view==='automations'?'Automations':view==='agents'?'Your crew':'Upgrade & equip','noop','aria-current="page"','tab-active')}<span>${view==='board'?'One ship. Many moving parts.':view==='automations'?`${rules().length} / ${cap.automations} active` :view==='agents'?`${state.agents.length} / ${cap.agents} assigned`:'Changes take effect immediately'}</span></div>
  <section class="runbar" aria-label="Run status"><div><span class="stat-icon">◷</span><span>Workday<strong>${state.day || 1}<small> / 10</small></strong></span></div><div><span class="stat-icon blue">ϟ</span><span>Actions left<strong>${state.actions}</strong></span></div><div><span class="stat-icon green">✓</span><span>Primary goals<strong>${complete}<small> / ${primary.length}</small></strong></span></div><div><span class="stat-icon purple">✧</span><span>Today’s score<strong>${state.dayScore}</strong></span></div><div><span class="coin">●</span><span>Coins<strong>${state.coins}</strong></span></div><div class="run-end">${state.phase==='playing'?button('End workday →','end',disabled(busy),'primary'):state.phase==='shop'?button('Start next day →','next',disabled(busy),'primary'):button('New cruise →','restart','','primary')}</div></section>
  ${state.phase==='lost'||state.phase==='won'?`<section class="outcome ${state.phase}"><strong>${state.phase==='won'?'Cruise complete. You kept everyone aboard!':'GAME OVER — The cruise is over.'}</strong><span>${state.phase==='won'?'10 days survived':`Unfinished Primary work on day ${state.day}`} · ${state.totalScore} total score</span>${button('Try a fresh cruise','restart','','primary')}</section>`:''}
  ${forecastView()}
  ${view==='board'?boardView():view==='automations'?automationView():view==='agents'?agentView():shopView()}
  <footer><span>ALL A BOARD! <b>·</b> Independently operated. Mildly haunted.</span><label>Animations <select id="speed"><option value="1" ${speed===1?'selected':''}>Normal</option><option value="3" ${speed===3?'selected':''}>Fast</option><option value="0" ${speed===0?'selected':''}>Off</option></select></label></footer></main>`;
  if(focusAction&&!busy&&focusAction!=='view'){const match=[...document.querySelectorAll('button[data-action]')].find(b=>b.dataset.action===focusAction&&b.dataset.id===focusId&&!b.disabled);match?.focus({preventScroll:true});}
}
function forecastView(){
  if(state.balanceVersion!==2)return '<aside class="forecast"><strong>Original cruise rules</strong><p>Start a new cruise for escalating workloads and forecast disruptions.</p></aside>';
  const tomorrow=state.phase==='shop',day=state.day+(tomorrow?1:0),items=tomorrow?state.tomorrow:state.items.filter(i=>i.lane==='primary'),events=(tomorrow?state.tomorrowEvents:state.events)||[];
  const turn=tomorrow?0:state.playerTurns||0;
  return `<aside class="forecast" aria-label="${tomorrow?'Tomorrow’s forecast':'Today’s forecast'}"><header><strong>${tomorrow?'Tomorrow’s forecast':'Today’s schedule'} · Day ${day}</strong><span>${items.length} Primary goals · ${tomorrow?'Plan purchases and crew assignments':'Turn '+turn+' completed'}</span></header><p>${DEPTS.map(d=>{const count=items.filter(i=>i.dept===d).length;return count?`${esc(d)}: ${count}`:'';}).filter(Boolean).join(' · ')}${BOSSES[day]?`<br>☠ Boss Task: ${esc(BOSSES[day].name)}`:''}</p><div class="forecast-events">${events.map(e=>`<article data-source="${e.id}" class="forecast-event ${e.resolved?'resolved':''} ${highlight?.source===e.id?'firing':''}"><strong>${e.resolved?'✓ ':''}${DISRUPTIONS[e.type]}${e.dept?' · '+esc(e.dept):''}</strong><span>${e.resolved?'Resolved':`After turn ${e.afterTurn} · ${Math.max(0,e.afterTurn-turn)} turns away`}</span><small>${e.type==='allhands'?'Lose 1 remaining action.':e.type==='inspection'?'Unfinished Galley work resets to Pending. Done work is safe.':'Assigned agents skip their next turn; passive perks stay active.'}</small></article>`).join('')||'<span>No scheduled disruptions.</span>'}</div>${!tomorrow?`<p class="starter-work">Auto-assign advanced ${state.daily.autoAssigned||0} Primary steps this morning.</p>`:''}${['disruption','reset','agent-skip'].includes(highlight?.kind)?`<div class="disruption-notice" role="status">${esc(highlight.message)}</div>`:''}</aside>`;
}
function boardGroups(){
  if(groupBy==='dept')return DEPTS.map((dept,n)=>({id:`dept-${dept}`,lane:null,info:{name:dept,color:['#008b62','#0089c9','#8063a7','#e43891'][n],label:'Grouped by department'},items:state.items.filter(i=>i.dept===dept)}));
  return Object.entries(laneInfo).map(([lane,info])=>({id:lane,lane,info,items:state.items.filter(i=>i.lane===lane)}));
}
function boardView(){
  const boss=BOSSES[state.day];
  return `<div class="board-toolbar"><div>${button('＋ Port of call','view',`data-view="shop"`,'primary small')}<label class="search">⌕ <input id="search" placeholder="Search work…" value="${esc(search)}" aria-label="Search work"></label><label class="group-filter">Group by <select id="group-by" aria-label="Group board by"><option value="eta" ${groupBy==='eta'?'selected':''}>ETA</option><option value="dept" ${groupBy==='dept'?'selected':''}>Department</option></select></label><span class="toolbar-caption">☷ ${groupBy==='eta'?'Due lane':'Department view'}</span></div><span class="live-state">${agentAction?`<i class="dot"></i> ${esc(AGENTS.find(a=>a.id===agentAction.id)?.name)} is acting…`:busy?'<i class="dot"></i> Resolving cascade…':state.pendingStuck?'A work scenario needs your call':state.phase==='shop'?'Workday complete · shop is open':'Click a status to advance · 1 action'}</span></div>
  ${boss?`<div class="boss-banner"><span>☠</span><div><strong>${esc(boss.name)}</strong><small>${esc(boss.rule)} The paperwork is mandatory.</small></div><b>BOSS TASK</b></div>`:''}
  <div class="board-scroll">${boardGroups().map(group=>{const {id,lane,info}=group;const items=group.items.filter(i=>(`${i.name} ${i.dept} ${i.targetName||''}`).toLowerCase().includes(search.toLowerCase()));
    return `<section class="board-group" style="--group:${info.color}"><div class="group-title">${button(`${collapsed.has(id)?'›':'⌄'} <strong>${info.name}</strong>`,'collapse',`data-id="${id}"`,'group-toggle')}<span>${items.filter(done).length} / ${items.length} completed</span><small>${info.label}</small></div>${collapsed.has(id)?'':`<table><colgroup><col style="width:38px"><col style="width:35%"><col style="width:155px"><col style="width:140px"><col style="width:110px"><col style="width:90px"><col style="width:100px"></colgroup><thead><tr><th aria-label="Completion">□</th><th>Item</th><th>Status</th><th>Department</th><th>Deadline</th><th>Points</th><th>Tag</th></tr></thead><tbody>${items.map(i=>`<tr id="${i.id}" class="${done(i)?'completed':''} ${highlight?.target===i.id?'row-highlight':''}"><td class="check">${done(i)?'☑':'□'}</td><td class="item-name"><div>${i.boss?'<span class="boss-icon">☠</span>':i.lane==='secondary'?'<span class="subtask-icon">↳</span>':''}<span>${esc(i.name)}</span>${i.preparedStatus?`<span class="prepared" title="Preparation carried this status into today">Prepared carry-over · ${['Pending','Working on it','In review'][i.preparedStatus]}</span>`:i.prepared?`<span class="prepared" title="Prepared yesterday">−${i.prepared} step</span>`:''}</div>${i.targetName?`<small>Tomorrow: ${esc(i.targetName)}</small>`:''}</td><td class="status-cell"><button data-action="advance" data-id="${i.id}" class="status ${i.stuck?'stuck':done(i)?'done':['pending','working','review'][i.status]}" title="${done(i)?'Completed':`Next step: ${['Working on it','In review','Done'][i.status]||'Done'}`}" ${disabled(busy||state.pendingStuck||state.phase!=='playing'||done(i)||!state.actions)} aria-label="${esc(i.name)}: ${status(i)}. ${done(i)?'Completed':i.stuck?'Resolve scenario':'Advance for one action'}">${status(i)}${!done(i)&&!i.stuck?'<span class="status-arrow"> →</span>':''}</button></td><td><span class="dept-label">${esc(i.dept)}</span></td><td><span class="deadline ${i.lane==='primary'&&!done(i)?'due':''}">${done(i)?'✓ Today':i.lane==='primary'?'◷ Today':i.lane==='secondary'?'Tomorrow':'Anytime'}</span></td><td>${i.points}<span class="muted"> pt</span></td><td>${i.tag==='Normal'?'<span class="muted">—</span>':`<span class="tag ${i.tag.toLowerCase()}">${i.tag}</span>`}</td></tr>`).join('')||'<tr><td colspan="7" class="empty-row">No tasks here. Enjoy this suspicious moment of calm.</td></tr>'}</tbody></table><div class="group-summary"><span>${groupBy==='dept'?'Department view · ':''}${lane==='primary'?'All required by end of day':lane==='secondary'?'Use the same status track; completion removes one step tomorrow':lane==='recurring'?'Optional work earns score, then bonus coins':'Primary, preparation, and recurring work shown together'}</span><span class="progress"><i style="width:${items.length?items.filter(done).length/items.length*100:0}%"></i></span></div>`}</section>`;
  }).join('')}</div>
  <section class="engine-strip"><div class="engine-label"><strong>Your engine</strong><small>${state.tier} plan</small></div><div class="engine-chips">${state.automations.filter(a=>a.enabled).map(a=>`<button data-action="view" data-view="automations" data-source="${a.id}" class="engine-chip ${highlight?.source===a.id?'firing':''}"><span>ϟ</span>${RULES.find(r=>r.id===a.id).name}</button>`).join('')}${state.agents.map(a=>{const def=AGENTS.find(x=>x.id===a.id),acting=agentAction?.id===a.id;return `<button data-action="view" data-view="agents" data-source="${a.id}" class="agent-chip ${highlight?.source===a.id||highlight?.source===`agent-action-${a.id}`?'firing':''} ${acting?'agent-moving':''}" id="agent-${a.id}">${portrait(def)}<span>${def.name}<small>${acting?'Taking action…':a.dept}</small></span></button>`;}).join('')}${state.agents.length===0?'<span class="muted crew-locked">♧ Crew unlocks with Pro</span>':''}</div></section>
  <section class="activity"><div class="activity-title"><strong>Activity log</strong><span>Live from the operations desk</span><b>${busy?'● LIVE':'✓ Up to date'}</b></div><div class="activity-lines" aria-label="Recent game events">${state.log.slice(-5).reverse().map((e,n)=>`<div class="log-line ${n===0?'latest':''}"><span class="log-dot ${e.kind==='score'?'score-dot':''}"></span><span>${esc(e.message)}</span><small>${n===0?'just now':''}</small></div>`).join('')}</div></section>`;
}
function automationView(){
  const cap=TIERS[state.tier];
  const cards=state.automations.map((a,n)=>{
    const r=RULES.find(r=>r.id===a.id);
    if(!`${r.name} ${r.text}`.toLowerCase().includes(ruleSearch.toLowerCase())||ruleRarity!=='All rarities'&&r.rarity!==ruleRarity)return '';
    return `<article class="automation-card" data-source="${a.id}"><div class="rule-number">${String(n+1).padStart(2,'0')}</div>
      <div class="rule-copy"><h3>${esc(r.text).replace(' → ',' <strong>→</strong> ')}</h3><div class="rule-meta"><b>${r.name}</b><span class="rarity ${r.rarity.toLowerCase()}">▥ ${r.rarity}</span><span>Owner ${portrait(AGENTS[0],'tiny')}</span><span>${a.enabled?'Active':'In reserve'}</span></div></div>
      <div class="rule-controls">${button('<i></i>','toggle',`data-id="${a.id}" role="switch" aria-checked="${a.enabled}" aria-label="Enable ${r.name}" ${disabled(!canManage()||!a.enabled&&rules().length>=cap.automations)}`,`toggle ${a.enabled?'on':''}`)}
      ${button('↑','up',`data-id="${a.id}" aria-label="Move ${r.name} earlier" ${disabled(!canManage()||n===0)}`,'icon-button')}
      ${button('↓','down',`data-id="${a.id}" aria-label="Move ${r.name} later" ${disabled(!canManage()||n===state.automations.length-1)}`,'icon-button')}
      <details class="rule-menu"><summary aria-label="More options for ${r.name}">···</summary>${button(`Sell · ${Math.floor(r.cost/2)} coins`,'sell',`data-id="${a.id}" ${disabled(!canManage())}`,'quiet small')}</details></div></article>`;
  }).join('');
  return `<section class="management"><div class="management-toolbar"><span>${canManage()?'Reorder, enable, or sell rules before the next day.':'Rules are locked during the workday. Make changes at port.'}</span>${button('Find automations ▾','view','data-view="shop"','primary')}</div>
    <div class="rule-filters"><label class="search">⌕ <input id="rule-search" value="${esc(ruleSearch)}" placeholder="Search automations" aria-label="Search automations"></label><select id="rule-rarity" aria-label="Filter automation rarity">${['All rarities','Common','Uncommon','Rare'].map(r=>`<option ${ruleRarity===r?'selected':''}>${r}</option>`).join('')}</select></div>
    <div class="automation-list">${cards||'<p class="empty-offers">No automations match these filters.</p>'}</div><div class="slot-grid">${Array.from({length:8},(_,i)=>`<div class="slot ${i>=cap.automations?'locked':''}"><b>${i<rules().length?'✓':i>=cap.automations?'♙':'＋'}</b><span>${i<rules().length?'Active slot':i>=cap.automations?`${i<5?'Pro':'Enterprise'} required`:'Available slot'}</span><small>Automation ${i+1}</small></div>`).join('')}</div></section>`;
}
function agentView(){
  const def=AGENTS.find(a=>a.id===selectedAgent),owned=state.agents.find(a=>a.id===def.id),canHire=canManage()&&!owned&&state.coins>=5&&state.agents.length<TIERS[state.tier].agents;
  return `<section class="agents-layout"><div><div class="management-toolbar"><span>One action from you. One action from each specialist.</span><span>${state.agents.length} / ${TIERS[state.tier].agents} slots</span></div><div class="agent-grid">${AGENTS.map(a=>{const own=state.agents.find(o=>o.id===a.id);return `<button data-action="select-agent" data-id="${a.id}" class="agent-card ${selectedAgent===a.id?'selected':''}" aria-pressed="${selectedAgent===a.id}">${portrait(a)}<h3>${a.name}</h3><span>${own?`<i class="dot"></i> ${own.dept}`:'Available to hire'}</span><small>5 coins · 1 / day</small></button>`;}).join('')}</div><div class="crew-explainer"><h3>Experts stay in their lane. Well, department.</h3><p>Primary work first. Then tomorrow’s preparations. Then recurring tasks. Each specialist acts after your move, choosing the closest-to-complete eligible task in their assigned department.</p><p>${state.tier==='basic'?'Upgrade to Pro to unlock your first two crew slots.':'Change assignments between days. Every agent costs 1 coin at the end of a successful day; unpaid agents leave.'}</p></div></div><aside class="agent-detail">${portrait(def,'large')}<div class="detail-copy"><span class="eyebrow">DEPARTMENT SPECIALIST</span><h2>${def.name}</h2><p>${def.perk}</p><div class="perk-label">✦ Passive perk</div><label>Assigned department<select id="assignment" data-id="${def.id}" ${disabled(!canManage()||!owned)}>${DEPTS.map(d=>`<option ${owned?.dept===d?'selected':''}>${d}</option>`).join('')}</select></label>${owned?'<div class="assigned-label">✓ On your crew · 1 coin / day</div>':button(state.tier==='basic'?'Pro plan required':'Hire specialist · 5 coins','hire',`data-id="${def.id}" ${disabled(!canHire)}`,'primary wide')}<small>${owned?'Assignment stays fixed throughout the workday.':'Hire at port, then choose a department.'}</small></div></aside></section>`;
}
function shopView(){
  const next=state.tier==='basic'?'pro':state.tier==='pro'?'enterprise':null;
  return `<section class="shop"><div class="port-banner"><div><span class="eyebrow">${state.phase==='shop'?'WELCOME TO PORT':'PORT OPENS AFTER A SUCCESSFUL WORKDAY'}</span><h2>A smoother tomorrow starts here.</h2><p>Buy a little breathing room. Or a spectacular chain reaction.</p></div><span class="port-illustration">≈<br>⚓</span></div><div class="shop-section-title"><h2>Automation offers</h2>${button(`↻ Reroll · ${2+state.rerolls} coins`,'reroll',disabled(!canManage()||state.coins<2+state.rerolls),'quiet')}</div><div class="offers">${state.offers.length?state.offers.map(id=>{const r=RULES.find(r=>r.id===id),parts=r.text.split(' → ');return `<article class="offer"><div class="offer-top"><span class="rarity ${r.rarity.toLowerCase()}">${r.rarity}</span><b>${r.cost} <span class="coin">●</span></b></div><h3>${r.name}</h3><div class="recipe"><span>${esc(parts[0])}</span><i>↓</i><strong>${esc(parts[1]||'Apply this rule to your board.')}</strong></div>${button(`Add automation · ${r.cost} coins`,'buy',`data-id="${id}" ${disabled(!canManage()||state.coins<r.cost)}`,'primary wide')}<small>${rules().length>=TIERS[state.tier].automations?'Added to reserve · disable another rule to equip.':'An open slot will enable this immediately.'}</small></article>`;}).join(''):'<div class="empty-offers">Offers arrive when you complete the day. Your engine’s next great idea is waiting.</div>'}</div><div class="shop-section-title"><h2>Your plan, upgraded</h2><span>Permanent for this cruise</span></div><div class="tier-grid">${Object.entries(TIERS).map(([id,t])=>`<article class="tier-card ${state.tier===id?'current':''}"><span class="eyebrow">${id.toUpperCase()}</span><h3>${id==='basic'?'Start small.':id==='pro'?'Delegate beautifully.':'Run the whole ship.'}</h3><p>${t.automations} automation slots<br>${t.agents} agent slots</p>${button(state.tier===id?'✓ Current plan':next===id?`Upgrade · ${t.cost} coins`:id==='basic'?'Included':'Requires Pro','upgrade',`data-id="${id}" ${disabled(!canManage()||next!==id||state.coins<t.cost)}`,state.tier===id?'current-label':'primary wide')}</article>`).join('')}</div><div class="shop-bottom"><div><h3>A crew makes all the difference.</h3><p>All specialists: 5 coins to hire, 1 coin per successful day.</p></div>${button('Meet the agents →','view','data-view="agents"','quiet')}</div></section>`;
}
function dialog(title,body,buttons){$('#overlay').innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><span class="eyebrow">ALL A BOARD!</span><h2 id="dialog-title">${title}</h2>${body}<div class="dialog-actions">${buttons}</div></section></div>`;$('#overlay button')?.focus();}
function showGameOver(){
  const unfinished=state.items.filter(i=>i.lane==='primary'&&!done(i));
  const incidents=state.log.filter(e=>['disruption','reset','agent-skip'].includes(e.kind));
  dialog('GAME OVER',`<p class="game-over-subtitle">THE CRUISE IS OVER.</p><p>Day ${state.day} ended with ${unfinished.length} unfinished Primary ${unfinished.length===1?'goal':'goals'}.</p><div class="game-over-stats"><span>Days survived<strong>${Math.max(0,state.day-1)}</strong></span><span>Final score<strong>${state.totalScore}</strong></span><span>Incidents<strong>${incidents.length}</strong></span></div><details open><summary>What went unfinished?</summary><ul>${unfinished.map(i=>`<li>${esc(i.name)} · ${status(i)} · ${Math.max(0,3-i.status)} steps remaining</li>`).join('')}</ul></details>${incidents.length?`<details><summary>Disruption history</summary><ul>${incidents.slice(-5).map(e=>`<li>${esc(e.message)}</li>`).join('')}</ul></details>`:''}`,button('Start a new cruise →','restart','','primary')+button('Inspect the board','close','','quiet'));
  $('.modal-backdrop').classList.add('game-over-backdrop');$('.modal').classList.add('game-over-modal');
}
function stuckScenario(item){
  const copy={
    Galley:['The captain has sent back the meal with one note: “make it more nautical.”','Caterer on call','Run the emergency tasting','☕'],
    Cabins:['The guest insists the air-conditioning is haunted. The air-conditioning has not denied it.','Send a specialist','Open the panel and investigate','⌂'],
    'Engine Room':['A warning light is blinking in a rhythm that feels increasingly personal.','Bring in outside engineering','Trace the circuit yourself','⚙'],
    Deck:['A pirate has filed a formal objection to the evening schedule. Their handwriting is impeccable.','Hire a negotiator','Handle the deck meeting','⚓'],
  }[item.dept];
  return {scene:copy[0],coin:copy[1],action:copy[2],icon:copy[3]};
}
function showStuckScenario(){
  const item=state.items.find(i=>i.id===state.pendingStuck);if(!item||$('.stuck-scenario'))return;
  const s=stuckScenario(item),canCoin=state.coins>=3,canAction=state.actions>=2;
  dialog(`${item.name} is Stuck`, `<div class="stuck-scenario"><div class="scenario-window"><span class="scenario-wave">≈</span><span class="scenario-alert">!</span><span class="scenario-icon">${s.icon}</span></div><p class="scenario-task"><b>${esc(item.dept)} incident</b><br>${esc(s.scene)}</p><p class="scenario-rule">Choose a route forward. Either option completes this task and resumes the workday.</p></div>`, `${button(`${esc(s.coin)} · 3 coins`,'resolve-stuck',`data-method="coins" ${disabled(!canCoin)}`,'scenario-option coins')} ${button(`${esc(s.action)} · 2 actions`,'resolve-stuck',`data-method="actions" ${disabled(!canAction)}`,'scenario-option actions')}`);
}
async function chooseTarget(title,items){return new Promise(resolve=>{dialog(esc(title),'<p>Choose the work order that gets the next step for free.</p>',items.map(i=>button(`${esc(i.name)} <small>${status(i)}</small>`,'choose-target',`data-id="${i.id}"`,'target-option')).join(''));$('#overlay').onclick=e=>{const b=e.target.closest('[data-action="choose-target"]');if(b){$('#overlay').innerHTML='';$('#overlay').onclick=null;resolve(b.dataset.id);}};});}
async function run(fn){if(busy)return;const oldPhase=state.phase;const active=document.activeElement?.dataset;const focusId=active?.id;busy=true;render();try{await fn();if(oldPhase==='playing'&&state.phase==='shop')view='shop';save();}catch(e){console.error(e);dialog('Something went overboard','<p>The last settled run is saved. Reload to recover it.</p>',button('Reload','reload','','primary'));}finally{busy=false;highlight=null;render();if(state.phase==='lost'&&oldPhase!=='lost')showGameOver();else if(state.pendingStuck)showStuckScenario();else if(focusId&&view==='board'){const row=document.getElementById(focusId);const next=row?.querySelector('button:not(:disabled)')||document.querySelector('[data-action="advance"]:not(:disabled)')||document.querySelector('.run-end button');next?.focus({preventScroll:true});}}}
document.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id}=b.dataset;
  if(action==='view'){view=b.dataset.view;render();window.scrollTo(0,0);return;}
  if(action==='collapse'){collapsed.has(id)?collapsed.delete(id):collapsed.add(id);render();return;}
  if(action==='select-agent'){selectedAgent=id;render();return;}
  if(action==='close'){$('#overlay').innerHTML='';return;}
  if(action==='reload'){location.reload();return;}
  if(action==='help'){dialog('Welcome aboard, operations manager.',`<p>Finish every green-group Primary goal before your actions run out. Every task follows Pending → Working on it → In review → Done, with some reviews becoming Stuck.</p><p>A Stuck task opens a short incident scenario: pay 3 coins for outside help or 2 actions to resolve it in-house. Blue-group preparations use that same status track and, once Done, save a step on their named goal tomorrow.</p><p>Primary workloads grow throughout the cruise. Check the forecast at port: all-hands costs an action, inspections reset unfinished Galley work, and briefings make affected agents skip a turn. Events happen after full turns, including your crew’s actions. Finishing early can avoid later events.</p><p>At port, buy automations and upgrade your plan. Pro unlocks agents, who take a department action after each of yours. Watch the log as your engine fires.</p>`,button('Got it, captain','close','','primary'));return;}
  if(busy)return;
  if(action==='restart'){dialog('Start a new cruise?',`<p>This replaces your current saved run. Enter a seed to replay the same ship and shop sequence.</p><label>Seed<input id="new-seed" type="number" min="0" max="4294967295" value="${Date.now()>>>0}"></label>`,button('Keep current cruise','close','','quiet')+button('Set sail','confirm-restart','','primary'));return;}
  if(action==='confirm-restart'){const seed=Number($('#new-seed').value);state=createState(Number.isFinite(seed)?seed:Date.now());buildGame();view='board';search='';$('#overlay').innerHTML='';await run(()=>game.startDay());return;}
  if(action==='advance'){await run(()=>game.act(id));return;}
  if(action==='resolve-stuck'){$('#overlay').innerHTML='';await run(()=>game.resolveStuck(b.dataset.method));return;}
  if(action==='end'){if(state.items.some(i=>i.lane==='primary'&&!done(i))){dialog('Leave mandatory work unfinished?','<p>Ending now will end your run. You can keep working while you have actions.</p>',button('Keep working','close','','primary')+button('End run','confirm-end','','quiet'));return;}await run(()=>game.endDay());return;}
  if(action==='confirm-end'){$('#overlay').innerHTML='';await run(()=>game.endDay());return;}
  if(action==='next'){view='board';await run(()=>game.startDay());return;}
  const changes={buy:()=>game.buy(id),hire:()=>game.hire(id),toggle:()=>game.toggle(id),up:()=>game.reorder(id,-1),down:()=>game.reorder(id,1),sell:()=>game.sell(id),upgrade:()=>game.upgrade(),reroll:()=>game.reroll()};
  if(changes[action]){changes[action]();save();render();}
});
document.addEventListener('input',e=>{if(['search','rule-search'].includes(e.target.id)){const id=e.target.id,pos=e.target.selectionStart;if(id==='search')search=e.target.value;else ruleSearch=e.target.value;render();$('#'+id).focus();$('#'+id).setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.id==='speed'){speed=Number(e.target.value);try{localStorage.setItem('aab-speed',speed);}catch{}}if(e.target.id==='rule-rarity'){ruleRarity=e.target.value;render();}if(e.target.id==='group-by'){groupBy=e.target.value;collapsed.clear();render();}if(e.target.id==='assignment'){game.assign(e.target.dataset.id,e.target.value);save();render();}});
document.addEventListener('keydown',e=>{const modal=$('.modal');if(!modal)return;const focusable=[...modal.querySelectorAll('button:not(:disabled),input,select,summary')];if(e.key==='Tab'&&focusable.length){const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}if(e.key==='Escape'&&!state.pendingStuck&&!$('#overlay [data-action="choose-target"]'))$('#overlay').innerHTML='';});
buildGame();render();if(state.phase==='new')run(()=>game.startDay());else if(state.pendingStuck)showStuckScenario();else if(state.phase==='lost')showGameOver();
